object juanita {
	var disfraz
	method disfraz(unDisfraz) {
		disfraz = unDisfraz
	}
	method visita(unaCasa) {
		unaCasa.darCaramelos(
			unaCasa.cuantosCaramelosDa(disfraz) + 2
		)
	}

}

object tito {

	method disfraz(disfraz) {
		//TODO: Autogenerated Code ! 
	}
	
}

object rolo {

}